// ui/src/views/System/reports/EDRReport.vue
<template>
  <div class="category-report report-print-ready">
    <ReportHeader
      title="EDR 检测专项报告"
      :subtitle="`${report.meta.onlineHosts} 台主机 · ${report.meta.enabledRules} 条规则启用`"
      :period="report.meta.period"
      :report-id="report.meta.reportID"
      :generated-at="report.meta.generatedAt"
    />
    <div class="export-bar no-print">
      <a-button type="primary" :loading="exporting" @click="exportPDF">
        <template #icon><FilePdfOutlined /></template>
        导出 PDF
      </a-button>
      <span class="export-bar__hint">服务端 Chromium 渲染 · 可搜索矢量文本</span>
    </div>
    <a-spin :spinning="loading">
      <!-- 元数据 -->
      <a-row :gutter="[16, 16]" class="stats-overview">
        <a-col :xs="12" :sm="8" :lg="{ span: 4, offset: 2 }">
          <a-card :bordered="false" class="stat-card">
            <a-statistic title="在线主机" :value="report.meta.onlineHosts" :value-style="{ color: '#22C55E' }" />
          </a-card>
        </a-col>
        <a-col :xs="12" :sm="8" :lg="4">
          <a-card :bordered="false" class="stat-card">
            <a-statistic title="启用规则" :value="report.meta.enabledRules" :value-style="{ color: '#3B82F6' }">
              <template #suffix>/ {{ report.meta.totalRules }}</template>
            </a-statistic>
          </a-card>
        </a-col>
        <a-col :xs="12" :sm="8" :lg="4">
          <a-card :bordered="false" class="stat-card">
            <a-statistic title="告警总数" :value="report.summary.totalAlerts" :value-style="{ color: '#F59E0B' }" />
          </a-card>
        </a-col>
        <a-col :xs="12" :sm="8" :lg="4">
          <a-card :bordered="false" class="stat-card">
            <a-statistic title="活跃告警" :value="report.summary.activeAlerts" :value-style="{ color: '#EF4444' }" />
          </a-card>
        </a-col>
        <a-col :xs="12" :sm="8" :lg="4">
          <a-card :bordered="false" class="stat-card">
            <a-statistic title="已忽略" :value="report.summary.ignoredAlerts" :value-style="{ color: '#86909C' }" />
          </a-card>
        </a-col>
      </a-row>

      <a-row :gutter="[16, 16]" class="stats-overview">
        <a-col :xs="12" :sm="8" :lg="{ span: 4, offset: 2 }">
          <a-card :bordered="false" class="stat-card">
            <a-statistic title="受影响主机" :value="report.summary.affectedHosts" :value-style="{ color: '#722ed1' }" />
          </a-card>
        </a-col>
        <a-col :xs="12" :sm="8" :lg="4">
          <a-card :bordered="false" class="stat-card">
            <a-statistic title="攻击故事线" :value="report.summary.totalStories" :value-style="{ color: '#3B82F6' }" />
          </a-card>
        </a-col>
        <a-col :xs="12" :sm="8" :lg="4">
          <a-card :bordered="false" class="stat-card">
            <a-statistic title="高危故事线" :value="report.summary.highRiskStories" :value-style="{ color: '#EF4444' }" />
          </a-card>
        </a-col>
        <a-col :xs="12" :sm="8" :lg="4">
          <a-card :bordered="false" class="stat-card">
            <a-statistic
              title="环比"
              :value="Math.abs(report.trend.growthPercent)"
              :precision="1"
              suffix="%"
              :value-style="{ color: trendColor }"
            >
              <template #prefix>{{ trendArrow }}</template>
            </a-statistic>
          </a-card>
        </a-col>
      </a-row>

      <!-- 严重程度 + Category 分布 -->
      <a-row :gutter="[16, 16]" style="margin-top: 16px">
        <a-col :xs="24" :lg="12">
          <a-card title="严重程度分布" :bordered="false">
            <VChart theme="mxsec" :option="severityOption" style="height: 320px" autoresize />
          </a-card>
        </a-col>
        <a-col :xs="24" :lg="12">
          <a-card title="MITRE ATT&CK 战术分布" :bordered="false">
            <VChart theme="mxsec" :option="tacticOption" style="height: 320px" autoresize />
          </a-card>
        </a-col>
      </a-row>

      <!-- Top 触发规则 + Top 主机 -->
      <a-row :gutter="[16, 16]" style="margin-top: 16px">
        <a-col :xs="24" :lg="12">
          <a-card title="Top 10 触发规则" :bordered="false">
            <a-table
              :columns="ruleColumns"
              :data-source="report.topRules"
              :pagination="false"
              size="small"
              row-key="title"
            >
              <template #bodyCell="{ column, record }">
                <template v-if="column.key === 'severity'">
                  <a-tag :color="severityColors[record.severity] || 'default'">
                    {{ severityLabelMap[record.severity] || record.severity }}
                  </a-tag>
                </template>
              </template>
            </a-table>
          </a-card>
        </a-col>
        <a-col :xs="24" :lg="12">
          <a-card title="Top 10 受影响主机" :bordered="false">
            <a-table
              :columns="hostColumns"
              :data-source="report.topHosts"
              :pagination="false"
              size="small"
              row-key="host_id"
            />
          </a-card>
        </a-col>
      </a-row>

      <!-- 原始事件量（ClickHouse） -->
      <a-row v-if="report.rawEventStats?.available" :gutter="[16, 16]" style="margin-top: 16px">
        <a-col :span="24">
          <a-card :bordered="false">
            <template #title>
              <span>原始事件量统计</span>
              <a-tag color="cyan" style="margin-left: 8px">ClickHouse 真实数据</a-tag>
            </template>
            <a-row :gutter="[16, 16]">
              <a-col :xs="12" :md="6">
                <a-statistic title="总事件数" :value="report.rawEventStats.totalEvents" :value-style="{ color: '#3B82F6' }" />
              </a-col>
              <a-col :xs="12" :md="6">
                <a-statistic title="活跃主机" :value="report.rawEventStats.uniqueHosts" :value-style="{ color: '#22C55E' }" />
              </a-col>
              <a-col :xs="12" :md="6">
                <a-statistic
                  title="平均/主机"
                  :value="report.rawEventStats.uniqueHosts > 0
                    ? Math.round(report.rawEventStats.totalEvents / report.rawEventStats.uniqueHosts)
                    : 0"
                  :value-style="{ color: '#F59E0B' }"
                />
              </a-col>
              <a-col :xs="12" :md="6">
                <a-statistic
                  title="告警转化率"
                  :value="alertConversionRate"
                  :precision="2"
                  suffix="%"
                  :value-style="{ color: '#722ed1' }"
                />
              </a-col>
            </a-row>
            <a-row :gutter="[16, 16]" style="margin-top: 16px">
              <a-col :xs="24" :lg="12">
                <div style="font-weight: 500; margin-bottom: 8px">事件类型分布</div>
                <VChart theme="mxsec" :option="eventTypeOption" style="height: 280px" autoresize />
              </a-col>
              <a-col :xs="24" :lg="12">
                <div style="font-weight: 500; margin-bottom: 8px">事件量趋势（小时）</div>
                <VChart theme="mxsec" :option="eventTrendOption" style="height: 280px" autoresize />
              </a-col>
            </a-row>
            <a-row :gutter="[16, 16]" style="margin-top: 16px">
              <a-col :xs="24" :lg="12">
                <div style="font-weight: 500; margin-bottom: 8px">Top 10 主机（按事件量）</div>
                <a-table
                  :columns="rawHostColumns"
                  :data-source="report.rawEventStats.topHostsByEvent"
                  :pagination="false"
                  size="small"
                  row-key="host_id"
                />
              </a-col>
              <a-col :xs="24" :lg="12">
                <div style="font-weight: 500; margin-bottom: 8px">Top 10 进程</div>
                <a-table
                  :columns="exeColumns"
                  :data-source="report.rawEventStats.topExe"
                  :pagination="false"
                  size="small"
                  row-key="exe"
                />
              </a-col>
            </a-row>
          </a-card>
        </a-col>
      </a-row>

      <!-- 自动响应 + IOC + 规则有效性 -->
      <a-row :gutter="[16, 16]" style="margin-top: 16px">
        <a-col :xs="24" :lg="8">
          <a-card title="自动响应执行" :bordered="false">
            <a-row :gutter="[12, 12]">
              <a-col :span="24">
                <a-statistic title="累计动作" :value="report.autoResponseStats?.total || 0" :value-style="{ color: '#722ed1' }" />
              </a-col>
              <a-col :span="8">
                <a-statistic title="网络封禁" :value="report.autoResponseStats?.networkBlocks || 0" :value-style="{ fontSize: '18px' }" />
              </a-col>
              <a-col :span="8">
                <a-statistic title="主机隔离" :value="report.autoResponseStats?.hostIsolations || 0" :value-style="{ fontSize: '18px' }" />
              </a-col>
              <a-col :span="8">
                <a-statistic title="进程查杀" :value="report.autoResponseStats?.processKills || 0" :value-style="{ fontSize: '18px' }" />
              </a-col>
            </a-row>
          </a-card>
        </a-col>
        <a-col :xs="24" :lg="8">
          <a-card title="IOC / 内存威胁" :bordered="false">
            <a-row :gutter="[12, 12]">
              <a-col :span="12">
                <a-statistic title="IOC 快照" :value="report.iocStats?.iocSnapshots || 0" :value-style="{ color: '#0891b2' }" />
              </a-col>
              <a-col :span="12">
                <a-statistic title="内存威胁" :value="report.iocStats?.memoryThreats || 0" :value-style="{ color: '#EF4444' }" />
              </a-col>
            </a-row>
            <div v-if="report.iocStats?.topIOCTypes?.length" style="margin-top: 12px">
              <div style="font-size: 12px; color: rgba(0,0,0,0.45); margin-bottom: 6px">Top 技术</div>
              <a-tag v-for="t in report.iocStats.topIOCTypes" :key="t.technique" color="red" style="margin-bottom: 4px">
                {{ t.technique }} ({{ t.count }})
              </a-tag>
            </div>
          </a-card>
        </a-col>
        <a-col :xs="24" :lg="8">
          <a-card title="规则有效性" :bordered="false">
            <a-statistic title="命中率" :value="report.ruleEfficacy?.hitRate || 0" :precision="1" suffix="%" :value-style="{ color: '#22C55E' }" />
            <a-progress
              :percent="Math.round(report.ruleEfficacy?.hitRate || 0)"
              :stroke-color="(report.ruleEfficacy?.hitRate || 0) > 50 ? '#22C55E' : '#F59E0B'"
              style="margin-top: 8px"
            />
            <div style="font-size: 12px; color: rgba(0,0,0,0.45); margin-top: 8px">
              {{ report.ruleEfficacy?.hitRules || 0 }} / {{ report.ruleEfficacy?.enabledRules || 0 }} 启用规则有命中
              · {{ report.ruleEfficacy?.zeroHitRules || 0 }} 条零命中
            </div>
          </a-card>
        </a-col>
      </a-row>

      <!-- 0 命中规则建议下线列表 -->
      <a-row v-if="report.ruleEfficacy?.topZeroHit?.length" :gutter="[16, 16]" style="margin-top: 16px">
        <a-col :span="24">
          <a-card title="零命中规则（建议复核或下线）" :bordered="false">
            <a-table
              :columns="zeroHitColumns"
              :data-source="report.ruleEfficacy.topZeroHit"
              :pagination="false"
              size="small"
              row-key="id"
            />
          </a-card>
        </a-col>
      </a-row>

      <!-- 改进建议 -->
      <a-row v-if="report.improvements?.length" :gutter="[16, 16]" style="margin-top: 16px">
        <a-col :span="24">
          <a-card title="改进建议" :bordered="false">
            <a-list :data-source="report.improvements" size="small">
              <template #renderItem="{ item, index }">
                <a-list-item>
                  <span style="color: #722ed1; margin-right: 8px">{{ index + 1 }}.</span>
                  {{ item }}
                </a-list-item>
              </template>
            </a-list>
          </a-card>
        </a-col>
      </a-row>

      <!-- Top 高危故事线 + 误报抑制 -->
      <a-row :gutter="[16, 16]" style="margin-top: 16px">
        <a-col :xs="24" :lg="14">
          <a-card title="Top 5 高风险攻击故事线" :bordered="false">
            <a-table
              :columns="storyColumns"
              :data-source="report.topStories"
              :pagination="false"
              size="small"
              row-key="story_id"
            >
              <template #bodyCell="{ column, record }">
                <template v-if="column.key === 'severity'">
                  <a-tag :color="severityColors[record.severity] || 'default'">
                    {{ severityLabelMap[record.severity] || record.severity }}
                  </a-tag>
                </template>
                <template v-else-if="column.key === 'risk_score'">
                  <a-progress
                    :percent="record.risk_score"
                    :stroke-color="record.risk_score >= 70 ? '#EF4444' : record.risk_score >= 40 ? '#F59E0B' : '#3B82F6'"
                    size="small"
                  />
                </template>
              </template>
            </a-table>
          </a-card>
        </a-col>
        <a-col :xs="24" :lg="10">
          <a-card title="误报抑制统计" :bordered="false">
            <a-table
              :columns="suppressColumns"
              :data-source="report.suppressionStats"
              :pagination="false"
              size="small"
              row-key="reason"
            />
            <a-empty v-if="!report.suppressionStats.length" description="无抑制记录" />
          </a-card>
        </a-col>
      </a-row>
    </a-spin>
    <ReportFooter
      :report-id="report.meta.reportID"
      :generated-at="report.meta.generatedAt"
      watermark="MXSEC CONFIDENTIAL"
    />
  </div>
</template>

<script setup lang="ts">
import { ref, computed, watch, onMounted } from 'vue'
import { message } from 'ant-design-vue'
import VChart from 'vue-echarts'
import { use } from 'echarts/core'
import { CanvasRenderer } from 'echarts/renderers'
import { PieChart, BarChart } from 'echarts/charts'
import {
  TitleComponent, TooltipComponent, LegendComponent, GridComponent,
} from 'echarts/components'
import type { EChartsOption } from 'echarts'
import type { Dayjs } from 'dayjs'
import { reportsApi, type EDRReport } from '@/api/reports'
import { FilePdfOutlined } from '@ant-design/icons-vue'
import ReportHeader from '@/components/report/ReportHeader.vue'
import ReportFooter from '@/components/report/ReportFooter.vue'

import { LineChart } from 'echarts/charts'
use([CanvasRenderer, PieChart, BarChart, LineChart, TitleComponent, TooltipComponent, LegendComponent, GridComponent])

const props = defineProps<{ dateRange: [Dayjs, Dayjs] }>()

const loading = ref(false)
const report = ref<EDRReport>({
  meta: { reportID: '', period: '', generatedAt: '', onlineHosts: 0, totalRules: 0, enabledRules: 0 },
  summary: { totalAlerts: 0, activeAlerts: 0, resolvedAlerts: 0, ignoredAlerts: 0, affectedHosts: 0, totalStories: 0, highRiskStories: 0 },
  severityDistribution: {},
  categoryDistribution: [],
  tacticDistribution: {},
  topRules: [],
  topHosts: [],
  topStories: [],
  suppressionStats: [],
  trend: { prevPeriodAlerts: 0, growthPercent: 0, direction: 'stable' },
  rawEventStats: { totalEvents: 0, uniqueHosts: 0, eventsByType: [], eventsByHour: [], topHostsByEvent: [], topExe: [], available: false },
  autoResponseStats: { networkBlocks: 0, hostIsolations: 0, processKills: 0, total: 0 },
  iocStats: { iocSnapshots: 0, memoryThreats: 0, topIOCTypes: [] },
  ruleEfficacy: { totalRules: 0, enabledRules: 0, hitRules: 0, zeroHitRules: 0, hitRate: 0, topZeroHit: [] },
  improvements: [],
})

const zeroHitColumns = [
  { title: 'ID', dataIndex: 'id', key: 'id', width: 80 },
  { title: '规则名', dataIndex: 'name', key: 'name', ellipsis: true },
  { title: '类别', dataIndex: 'category', key: 'category', width: 180 },
]

const alertConversionRate = computed(() => {
  const ev = report.value.rawEventStats?.totalEvents || 0
  const al = report.value.summary?.totalAlerts || 0
  return ev > 0 ? (al / ev) * 100 : 0
})

const eventTypeOption = computed<EChartsOption>(() => ({
  tooltip: { trigger: 'item', formatter: '{b}: {c} ({d}%)' },
  legend: { orient: 'vertical', left: 'left', textStyle: { fontSize: 11 } },
  series: [{
    name: '事件类型', type: 'pie', radius: ['40%', '70%'],
    itemStyle: { borderRadius: 6, borderColor: '#fff', borderWidth: 2 },
    label: { show: false }, labelLine: { show: false },
    data: (report.value.rawEventStats?.eventsByType || []).map(e => ({
      value: Number(e.count), name: e.event_type,
    })),
  }],
}))

const eventTrendOption = computed<EChartsOption>(() => {
  const data = report.value.rawEventStats?.eventsByHour || []
  return {
    tooltip: { trigger: 'axis' },
    grid: { left: '3%', right: '4%', bottom: '3%', containLabel: true },
    xAxis: {
      type: 'category',
      data: data.map(d => d.hour.slice(5)),
      axisLabel: { rotate: 45, fontSize: 10, interval: Math.max(0, Math.floor(data.length / 12)) },
    },
    yAxis: { type: 'value' },
    series: [{
      name: '事件量', type: 'line', smooth: true,
      areaStyle: { opacity: 0.3 },
      data: data.map(d => Number(d.count)),
      itemStyle: { color: '#3B82F6' },
    }],
  }
})

const rawHostColumns = [
  { title: '主机', key: 'hostname', dataIndex: 'hostname', ellipsis: true },
  { title: '事件量', key: 'count', dataIndex: 'count', width: 110, align: 'right' as const },
]

const exeColumns = [
  { title: '进程路径', key: 'exe', dataIndex: 'exe', ellipsis: true },
  { title: '事件量', key: 'count', dataIndex: 'count', width: 110, align: 'right' as const },
]

const severityColors: Record<string, string> = {
  critical: '#dc2626', high: '#ea580c', medium: '#ca8a04', low: '#0891b2',
}
const severityLabelMap: Record<string, string> = {
  critical: '严重', high: '高危', medium: '中危', low: '低危',
}

const tacticLabelMap: Record<string, string> = {
  initial_access: '初始访问', execution: '执行', persistence: '持久化',
  privilege_escalation: '权限提升', defense_evasion: '防御规避',
  credential_access: '凭据访问', discovery: '发现', lateral_movement: '横向移动',
  collection: '收集', exfiltration: '数据渗出', command_and_control: 'C2 通信',
  impact: '影响', other: '其他',
}

const trendColor = computed(() =>
  report.value.trend.direction === 'up' ? '#EF4444'
    : report.value.trend.direction === 'down' ? '#22C55E' : '#86909C'
)
const trendArrow = computed(() =>
  report.value.trend.direction === 'up' ? '↑'
    : report.value.trend.direction === 'down' ? '↓' : '→'
)

const severityOption = computed<EChartsOption>(() => ({
  tooltip: { trigger: 'item', formatter: '{b}: {c} ({d}%)' },
  legend: { orient: 'vertical', left: 'left' },
  series: [{
    name: '严重级别', type: 'pie', radius: ['40%', '70%'],
    itemStyle: { borderRadius: 8, borderColor: '#fff', borderWidth: 2 },
    data: (['critical', 'high', 'medium', 'low'] as const)
      .map(sev => ({
        value: report.value.severityDistribution[sev] || 0,
        name: severityLabelMap[sev],
        itemStyle: { color: severityColors[sev] },
      }))
      .filter(item => item.value > 0),
  }],
}))

const tacticOption = computed<EChartsOption>(() => {
  const entries = Object.entries(report.value.tacticDistribution)
    .filter(([, v]) => v > 0)
    .sort((a, b) => b[1] - a[1])
  return {
    tooltip: { trigger: 'axis', axisPointer: { type: 'shadow' } },
    grid: { left: '3%', right: '4%', bottom: '3%', containLabel: true },
    xAxis: {
      type: 'category',
      data: entries.map(([k]) => tacticLabelMap[k] || k),
      axisLabel: { rotate: 30, interval: 0 },
    },
    yAxis: { type: 'value' },
    series: [{
      name: '告警数', type: 'bar',
      data: entries.map(([, v]) => v),
      itemStyle: { color: '#722ed1' },
    }],
  }
})

const ruleColumns = [
  { title: '规则', key: 'title', dataIndex: 'title', ellipsis: true },
  { title: '级别', key: 'severity', width: 80 },
  { title: '命中', key: 'count', dataIndex: 'count', width: 80 },
]

const hostColumns = [
  { title: '主机', key: 'hostname', dataIndex: 'hostname', ellipsis: true },
  { title: '告警数', key: 'count', dataIndex: 'count', width: 90 },
]

const storyColumns = [
  { title: '主机', key: 'hostname', dataIndex: 'hostname', ellipsis: true, width: 200 },
  { title: '阶段', key: 'phase', dataIndex: 'phase', width: 130 },
  { title: '级别', key: 'severity', width: 70 },
  { title: '事件', key: 'event_count', dataIndex: 'event_count', width: 70 },
  { title: '告警', key: 'alert_count', dataIndex: 'alert_count', width: 70 },
  { title: '风险', key: 'risk_score', width: 130 },
]

const suppressColumns = [
  { title: '抑制原因', key: 'reason', dataIndex: 'reason', ellipsis: true },
  { title: '数量', key: 'count', dataIndex: 'count', width: 80 },
]

const loadData = async () => {
  loading.value = true
  try {
    const data = await reportsApi.getEDRReport({
      start_time: props.dateRange[0].format('YYYY-MM-DD'),
      end_time: props.dateRange[1].format('YYYY-MM-DD'),
    })
    report.value = data
  } catch (e) {
    console.error('加载 EDR 报告失败:', e)
  } finally {
    loading.value = false
  }
}

const exporting = ref(false)
const exportPDF = async () => {
  exporting.value = true
  try {
    const blob = await reportsApi.exportEDRPDF({
      start_time: props.dateRange[0].format('YYYY-MM-DD'),
      end_time: props.dateRange[1].format('YYYY-MM-DD'),
    })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `EDR-Report-${props.dateRange[1].format('YYYYMMDD')}.pdf`
    a.click()
    URL.revokeObjectURL(url)
    message.success('PDF 已生成')
  } catch (e: any) {
    console.error('PDF 导出失败:', e)
  } finally {
    exporting.value = false
  }
}

defineExpose({ loadData })

watch(() => props.dateRange, loadData, { deep: true })
onMounted(loadData)
</script>

<style scoped>
.category-report {
  padding: 0;
}
.stats-overview {
  margin-bottom: 0;
}
.stat-card {
  text-align: center;
}
.export-bar {
  display: flex;
  align-items: center;
  gap: 12px;
  margin-bottom: 16px;
  padding: 8px 16px;
  background: rgba(34, 197, 94, 0.06);
  border-left: 3px solid #22c55e;
  border-radius: 6px;

  &__hint {
    color: rgba(0, 0, 0, 0.45);
    font-size: 12px;
  }
}
</style>

// web/src/app/(console)/operations/reports/_views/EdrReport.tsx
"use client";
import { useQuery } from "@tanstack/react-query";
import { useTranslation } from "react-i18next";
import {
  AlertTriangle,
  Download,
  Shield,
  ShieldCheck,
  ShieldOff,
  Activity,
  Cpu,
  Globe,
  Zap,
  BookOpen,
  Eye,
  MinusCircle,
  TrendingUp,
  TrendingDown,
  Minus,
} from "lucide-react";
import { reportsApi } from "@/lib/api/reports";
import type { DateRange } from "@/lib/api/reports";
import { Button } from "@/components/ui/Button";
import { Card, CardHeader } from "@/components/ui/Card";
import { ChartCard } from "@/components/ui/ChartCard";
import { DataTable } from "@/components/ui/DataTable";
import { EmptyState } from "@/components/ui/EmptyState";
import { StatCard } from "@/components/ui/StatCard";
import { SeverityTag } from "@/components/ui/Tag";
import type { Column } from "@/components/ui/DataTable";
import type { Severity } from "@/lib/api/types";

interface Props {
  range: DateRange;
}

const SEV_COLORS: Record<string, string> = {
  critical: "#EF4444",
  high: "#F97316",
  medium: "#FBBF24",
  low: "#94A3B8",
};

const TACTIC_COLORS: Record<string, string> = {
  initial_access: "#EF4444",
  execution: "#F97316",
  persistence: "#FB923C",
  privilege_escalation: "#FBBF24",
  defense_evasion: "#A78BFA",
  credential_access: "#EC4899",
  discovery: "#38BDF8",
  lateral_movement: "#34D399",
  collection: "#6EE7B7",
  exfiltration: "#F472B6",
  command_and_control: "#818CF8",
  impact: "#DC2626",
  other: "#94A3B8",
};

export function EdrReport({ range }: Props) {
  const { t } = useTranslation();

  const SEV_LABEL: Record<string, string> = {
    critical: t("common.severity.critical"),
    high: t("common.severity.high"),
    medium: t("common.severity.medium"),
    low: t("common.severity.low"),
  };

  const { data, isLoading } = useQuery({
    queryKey: ["reports-edr", range.start, range.end],
    queryFn: () => reportsApi.edrModule(range),
  });

  function handleExportPdf() {
    void reportsApi.downloadPdf(
      "/reports/edr/pdf",
      { start_time: range.start, end_time: range.end },
      "edr-report.pdf",
    );
  }

  if (isLoading && !data) {
    return <Card className="p-10 text-center text-muted">{t("operations.reports.loading")}</Card>;
  }

  if (!data) {
    return <EmptyState title={t("operations.reports.emptyData")} desc="" />;
  }

  const {
    meta,
    summary,
    severityDistribution,
    tacticDistribution,
    topRules,
    topHosts,
    topStories,
    suppressionStats,
    trend,
    rawEventStats,
    autoResponseStats,
    iocStats,
    ruleEfficacy,
    improvements,
  } = data;

  // --- Trend display ---
  const growthAbs = Math.abs(trend?.growthPercent ?? 0).toFixed(1);
  const trendLabel =
    trend?.direction === "up"
      ? `↑ ${growthAbs}%`
      : trend?.direction === "down"
        ? `↓ ${growthAbs}%`
        : `→ ${growthAbs}%`;

  // --- Chart: severity pie ---
  const sevEntries = Object.entries(severityDistribution ?? {}).filter(([, v]) => v > 0);
  const severityOption = {
    tooltip: { trigger: "item", formatter: "{b}: {c} ({d}%)" },
    legend: { orient: "vertical", left: "left" },
    series: [
      {
        type: "pie",
        radius: ["40%", "70%"],
        data: sevEntries.map(([name, value]) => ({
          name: SEV_LABEL[name] ?? name,
          value,
          itemStyle: { color: SEV_COLORS[name] },
        })),
      },
    ],
  };

  // --- Chart: tactic bar ---
  const tacticEntries = Object.entries(tacticDistribution ?? {})
    .filter(([, v]) => v > 0)
    .sort(([, a], [, b]) => (b as number) - (a as number));
  const tacticOption = {
    tooltip: { trigger: "axis", axisPointer: { type: "shadow" } },
    grid: { left: "3%", right: "8%", bottom: "3%", containLabel: true },
    xAxis: { type: "value" },
    yAxis: {
      type: "category",
      data: tacticEntries.map(([k]) => k),
    },
    series: [
      {
        type: "bar",
        data: tacticEntries.map(([k, v]) => ({
          value: v,
          itemStyle: { color: TACTIC_COLORS[k] ?? "#6366F1" },
        })),
      },
    ],
  };

  // --- Chart: event type pie (rawEventStats) ---
  const eventsByTypeEntries = (rawEventStats?.eventsByType ?? []).filter((r) => r.count > 0);
  const eventsByTypeOption = {
    tooltip: { trigger: "item", formatter: "{b}: {c} ({d}%)" },
    legend: { orient: "vertical", left: "left", type: "scroll" },
    series: [
      {
        type: "pie",
        radius: ["35%", "65%"],
        data: eventsByTypeEntries.map((r) => ({ name: r.event_type, value: r.count })),
      },
    ],
  };

  // --- Chart: events by hour line ---
  const eventsByHour = rawEventStats?.eventsByHour ?? [];
  const eventsByHourOption = {
    tooltip: { trigger: "axis" },
    grid: { left: "3%", right: "4%", bottom: "3%", containLabel: true },
    xAxis: {
      type: "category",
      data: eventsByHour.map((r) => String(r.hour)),
      axisLabel: { rotate: 30, fontSize: 10 },
    },
    yAxis: { type: "value" },
    series: [
      {
        type: "line",
        smooth: true,
        data: eventsByHour.map((r) => r.count),
        itemStyle: { color: "#3B82F6" },
        areaStyle: { color: "rgba(59,130,246,0.1)" },
      },
    ],
  };

  // --- Table types ---
  type TopRule = (typeof topRules)[number];
  type TopHost = (typeof topHosts)[number];
  type TopStory = (typeof topStories)[number];
  type TopHostByEvent = NonNullable<typeof rawEventStats>["topHostsByEvent"][number];
  type TopExe = NonNullable<typeof rawEventStats>["topExe"][number];
  type ZeroHit = (typeof ruleEfficacy.topZeroHit)[number];
  type Suppress = (typeof suppressionStats)[number];

  // --- Table columns ---
  const ruleColumns: Column<TopRule>[] = [
    { key: "title", title: t("operations.reports.edrColTitle") },
    { key: "category", title: t("operations.reports.colCategory"), width: "130px" },
    {
      key: "severity",
      title: t("operations.reports.colSeverity"),
      width: "100px",
      render: (r) => <SeverityTag level={r.severity as Severity} />,
    },
    { key: "count", title: t("operations.reports.edrColCount"), align: "right", width: "90px" },
  ];

  const hostColumns: Column<TopHost>[] = [
    { key: "hostname", title: t("operations.reports.edrColHostname") },
    { key: "count", title: t("operations.reports.edrColCount"), align: "right", width: "100px" },
  ];

  const storyColumns: Column<TopStory>[] = [
    { key: "hostname", title: t("operations.reports.edrColHostname"), width: "160px" },
    { key: "phase", title: t("operations.reports.edrColPhase"), width: "130px" },
    {
      key: "severity",
      title: t("operations.reports.colSeverity"),
      width: "100px",
      render: (r) => <SeverityTag level={r.severity as Severity} />,
    },
    {
      key: "event_count",
      title: t("operations.reports.edrColEventCount"),
      align: "right",
      width: "80px",
    },
    {
      key: "alert_count",
      title: t("operations.reports.edrColAlertCount"),
      align: "right",
      width: "80px",
    },
    {
      key: "risk_score",
      title: t("operations.reports.edrColRiskScore"),
      align: "right",
      width: "90px",
      render: (r) => r.risk_score.toFixed(1),
    },
  ];

  const topHostByEventColumns: Column<TopHostByEvent>[] = [
    { key: "hostname", title: t("operations.reports.edrColHostname") },
    { key: "count", title: t("operations.reports.edrColCount"), align: "right", width: "100px" },
  ];

  const topExeColumns: Column<TopExe>[] = [
    { key: "exe", title: t("operations.reports.edrColExe") },
    { key: "count", title: t("operations.reports.edrColCount"), align: "right", width: "100px" },
  ];

  const zeroHitColumns: Column<ZeroHit>[] = [
    { key: "name", title: t("operations.reports.edrColRuleName") },
    { key: "category", title: t("operations.reports.edrColRuleCategory"), width: "140px" },
  ];

  const suppressColumns: Column<Suppress>[] = [
    { key: "reason", title: t("operations.reports.edrColReason") },
    {
      key: "count",
      title: t("operations.reports.edrColCount"),
      align: "right",
      width: "100px",
    },
  ];

  // Computed for raw events block
  const avgPerHost =
    rawEventStats?.uniqueHosts && rawEventStats.uniqueHosts > 0
      ? Math.round(rawEventStats.totalEvents / rawEventStats.uniqueHosts)
      : 0;
  const alertConvRate =
    rawEventStats?.totalEvents && rawEventStats.totalEvents > 0
      ? ((summary.totalAlerts / rawEventStats.totalEvents) * 100).toFixed(3)
      : "—";

  return (
    <div className="space-y-6">
      {/* Export PDF */}
      <div className="flex justify-end">
        <Button variant="ghost" onClick={handleExportPdf}>
          <Download size={15} />
          {t("operations.reports.exportPdf")}
        </Button>
      </div>

      {/* === Section 1: Meta StatCards Row 1 — online hosts / enabled rules / total alerts / active / ignored === */}
      <div className="grid grid-cols-2 gap-4 md:grid-cols-5">
        <StatCard
          label={t("operations.reports.edrOnlineHosts")}
          value={meta.onlineHosts}
          icon={Shield}
        />
        <StatCard
          label={`${t("operations.reports.edrEnabledRules")} / ${t("operations.reports.edrTotalRules")}`}
          value={`${meta.enabledRules} / ${meta.totalRules}`}
          icon={ShieldCheck}
          tone="success"
        />
        <StatCard
          label={t("operations.reports.edrTotalAlerts")}
          value={summary.totalAlerts}
          icon={AlertTriangle}
          tone="danger"
        />
        <StatCard
          label={t("operations.reports.edrActive")}
          value={summary.activeAlerts}
          icon={Activity}
          tone="warning"
        />
        <StatCard
          label={t("operations.reports.edrIgnoredAlerts")}
          value={summary.ignoredAlerts}
          icon={MinusCircle}
        />
      </div>

      {/* === Section 1b: Meta StatCards Row 2 — affected hosts / stories / high-risk stories / trend === */}
      <div className="grid grid-cols-2 gap-4 md:grid-cols-4">
        <StatCard
          label={t("operations.reports.edrAffectedHosts")}
          value={summary.affectedHosts}
          icon={Globe}
          tone="warning"
        />
        <StatCard
          label={t("operations.reports.edrTotalStories")}
          value={summary.totalStories}
          icon={BookOpen}
        />
        <StatCard
          label={t("operations.reports.edrHighRiskStories")}
          value={summary.highRiskStories}
          icon={ShieldOff}
          tone="danger"
        />
        {trend && (
          <StatCard
            label={t("operations.reports.edrTrend")}
            value={trendLabel}
            icon={trend.direction === "up" ? TrendingUp : trend.direction === "down" ? TrendingDown : Minus}
            tone={trend.direction === "up" ? "danger" : trend.direction === "down" ? "success" : "default"}
          />
        )}
      </div>

      {/* === Section 2: Charts — severity pie + MITRE tactic bar === */}
      <div className="grid grid-cols-1 gap-4 lg:grid-cols-2">
        {sevEntries.length > 0 && (
          <ChartCard title={t("operations.reports.edrSeverityDist")} option={severityOption} />
        )}
        {tacticEntries.length > 0 && (
          <ChartCard
            title={t("operations.reports.edrTactic")}
            option={tacticOption}
            height={tacticEntries.length > 8 ? 360 : 280}
          />
        )}
      </div>

      {/* === Section 3: Top10 规则 + Top10 主机 === */}
      <Card>
        <CardHeader title={t("operations.reports.edrTopRules")} />
        <DataTable<TopRule>
          columns={ruleColumns}
          rows={topRules ?? []}
          rowKey={(r) => r.title}
        />
      </Card>

      <Card>
        <CardHeader title={t("operations.reports.edrTopHosts")} />
        <DataTable<TopHost>
          columns={hostColumns}
          rows={topHosts ?? []}
          rowKey={(r) => r.host_id}
        />
      </Card>

      {/* === Section 4: ClickHouse 原始事件块 (conditional on available) === */}
      {rawEventStats?.available && (
        <div className="space-y-4">
          <h3 className="text-sm font-semibold text-foreground">
            {t("operations.reports.edrRawEventsTitle")}
          </h3>

          {/* 4 stat cards */}
          <div className="grid grid-cols-2 gap-4 md:grid-cols-4">
            <StatCard
              label={t("operations.reports.edrTotalEvents")}
              value={rawEventStats.totalEvents.toLocaleString()}
              icon={Activity}
            />
            <StatCard
              label={t("operations.reports.edrUniqueHosts")}
              value={rawEventStats.uniqueHosts}
              icon={Cpu}
            />
            <StatCard
              label={t("operations.reports.edrAvgPerHost")}
              value={avgPerHost.toLocaleString()}
              icon={Eye}
            />
            <StatCard
              label={t("operations.reports.edrAlertConvRate")}
              value={alertConvRate === "—" ? "—" : `${alertConvRate}%`}
              icon={Zap}
            />
          </div>

          {/* event type pie + hourly trend line */}
          <div className="grid grid-cols-1 gap-4 lg:grid-cols-2">
            {eventsByTypeEntries.length > 0 && (
              <ChartCard
                title={t("operations.reports.edrEventsByType")}
                option={eventsByTypeOption}
              />
            )}
            {eventsByHour.length > 0 && (
              <ChartCard
                title={t("operations.reports.edrEventsByHour")}
                option={eventsByHourOption}
                height={280}
              />
            )}
          </div>

          {/* top hosts by event */}
          {(rawEventStats.topHostsByEvent ?? []).length > 0 && (
            <Card>
              <CardHeader title={t("operations.reports.edrTopHostsByEvent")} />
              <DataTable<TopHostByEvent>
                columns={topHostByEventColumns}
                rows={rawEventStats.topHostsByEvent}
                rowKey={(r) => r.host_id}
              />
            </Card>
          )}

          {/* top exe */}
          {(rawEventStats.topExe ?? []).length > 0 && (
            <Card>
              <CardHeader title={t("operations.reports.edrTopExe")} />
              <DataTable<TopExe>
                columns={topExeColumns}
                rows={rawEventStats.topExe}
                rowKey={(r) => r.exe}
              />
            </Card>
          )}
        </div>
      )}

      {/* === Section 5: 自动响应卡 === */}
      {autoResponseStats && (
        <div className="space-y-2">
          <h3 className="text-sm font-semibold text-foreground">
            {t("operations.reports.edrAutoResponseTitle")}
          </h3>
          <div className="grid grid-cols-2 gap-4 md:grid-cols-4">
            <StatCard
              label={t("operations.reports.edrNetworkBlocks")}
              value={autoResponseStats.networkBlocks}
              icon={Globe}
              tone="danger"
            />
            <StatCard
              label={t("operations.reports.edrHostIsolations")}
              value={autoResponseStats.hostIsolations}
              icon={ShieldOff}
              tone="warning"
            />
            <StatCard
              label={t("operations.reports.edrProcessKills")}
              value={autoResponseStats.processKills}
              icon={Zap}
              tone="warning"
            />
            <StatCard
              label={t("operations.reports.edrAutoTotal")}
              value={autoResponseStats.total}
              icon={Activity}
            />
          </div>
        </div>
      )}

      {/* === Section 6: IOC / 内存威胁卡 === */}
      {iocStats && (
        <div className="space-y-2">
          <h3 className="text-sm font-semibold text-foreground">
            {t("operations.reports.edrIocTitle")}
          </h3>
          <div className="flex flex-wrap gap-4">
            <StatCard
              label={t("operations.reports.edrIocSnapshots")}
              value={iocStats.iocSnapshots}
              icon={Eye}
            />
            <StatCard
              label={t("operations.reports.edrMemoryThreats")}
              value={iocStats.memoryThreats}
              icon={ShieldOff}
              tone="danger"
            />
          </div>
          {(iocStats.topIOCTypes ?? []).length > 0 && (
            <div className="flex flex-wrap gap-2 pt-1">
              <span className="text-xs text-muted">{t("operations.reports.edrTopIOCTypes")}：</span>
              {iocStats.topIOCTypes.map((item) => (
                <span
                  key={item.technique}
                  className="rounded-full border border-border bg-surface px-2 py-0.5 text-xs"
                >
                  {item.technique}
                  <span className="ml-1 text-muted">×{item.count}</span>
                </span>
              ))}
            </div>
          )}
        </div>
      )}

      {/* === Section 7: 规则有效性卡 + 零命中规则表 === */}
      {ruleEfficacy && (
        <div className="space-y-4">
          <h3 className="text-sm font-semibold text-foreground">
            {t("operations.reports.edrRuleEfficacyTitle")}
          </h3>
          <div className="grid grid-cols-2 gap-4 md:grid-cols-4">
            <StatCard
              label={t("operations.reports.edrHitRules")}
              value={ruleEfficacy.hitRules}
              icon={ShieldCheck}
              tone="success"
            />
            <StatCard
              label={t("operations.reports.edrEnabledRules")}
              value={ruleEfficacy.enabledRules}
              icon={Shield}
            />
            <StatCard
              label={t("operations.reports.edrZeroHitRules")}
              value={ruleEfficacy.zeroHitRules}
              icon={ShieldOff}
              tone={ruleEfficacy.zeroHitRules > 20 ? "danger" : "default"}
            />
            <StatCard
              label={t("operations.reports.edrHitRate")}
              value={`${ruleEfficacy.hitRate.toFixed(1)}%`}
              icon={Activity}
              tone={ruleEfficacy.hitRate >= 50 ? "success" : "warning"}
            />
          </div>
          {/* hit rate progress bar */}
          <Card className="p-4">
            <div className="mb-1 flex justify-between text-xs text-muted">
              <span>{t("operations.reports.edrHitRate")}</span>
              <span>{ruleEfficacy.hitRate.toFixed(1)}%</span>
            </div>
            <div className="h-2 w-full overflow-hidden rounded-full bg-surface-alt">
              <div
                className="h-full rounded-full bg-blue-500 transition-all"
                style={{ width: `${Math.min(ruleEfficacy.hitRate, 100)}%` }}
              />
            </div>
          </Card>

          {(ruleEfficacy.topZeroHit ?? []).length > 0 && (
            <Card>
              <CardHeader title={t("operations.reports.edrZeroHitTable")} />
              <DataTable<ZeroHit>
                columns={zeroHitColumns}
                rows={ruleEfficacy.topZeroHit}
                rowKey={(r) => String(r.id)}
              />
            </Card>
          )}
        </div>
      )}

      {/* === Section 8: 改进建议 === */}
      {(improvements ?? []).length > 0 && (
        <Card className="p-4">
          <h3 className="mb-3 text-sm font-semibold text-foreground">
            {t("operations.reports.edrImprovementsTitle")}
          </h3>
          <ol className="list-inside list-decimal space-y-2">
            {improvements.map((item, i) => (
              <li key={i} className="text-sm text-foreground">
                {item}
              </li>
            ))}
          </ol>
        </Card>
      )}

      {/* === Section 9: Top5 高风险故事线 === */}
      {(topStories ?? []).length > 0 && (
        <Card>
          <CardHeader title={t("operations.reports.edrTopStoriesTitle")} />
          <DataTable<TopStory>
            columns={storyColumns}
            rows={topStories}
            rowKey={(r) => r.story_id}
          />
        </Card>
      )}

      {/* === Section 10: 误报抑制统计 === */}
      {(suppressionStats ?? []).length > 0 && (
        <Card>
          <CardHeader title={t("operations.reports.edrSuppressionTitle")} />
          <DataTable<Suppress>
            columns={suppressColumns}
            rows={suppressionStats}
            rowKey={(r) => r.reason}
          />
        </Card>
      )}
    </div>
  );
}
